# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b77ce95d3f9cb007ac0d9c12c46f7e0617cc5f5d910e857c5403136e013dcf59d3358469061adc065ba90bc149218b1b51cbb10bde622bf43772f30ab1a364e

test:
  secret_key_base: f32f15100e69b2b69341ed6cf06eacadad0912b72de98b73de6b47031fa088db9968ad5cf9a752b82d2b1117e7e3c3861a6f2335e180e39203fc77644e157d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
